spring:
  application:
    name: eureka-server
  # security密码验证
  security:
    user:
      # 用户名
      name: user
      # 密码
      password: abc123456
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
#      globalcors:
#        corsConfigurations:
#          '[/**]':
#            allowedOrigins: "*"
#            exposedHeaders: content-type
#            allowedHeaders: content-type
#            allowCredentials: true
#            allowedMethods:
#              - GET
#              - OPTIONS
#              - PUT
#              - DELETE
#              - POST

server:
  port: 8761

eureka:
  client:
    # 由于该应用为注册中心, 所以设置为false, 代表不向注册中心注册自己
    register-with-eureka: false
    # 由于注册中心的职责就是维护服务实例, 它并不需要去检索服务, 所以也设置为 false
    fetch-registry: false
    service-url:
      defaultZone: http://user:abc123456@localhost:${server.port}/eureka/
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#  instance:
#    hostname: eureka-server
#    prefer-ip-address: true

  server:
    # 在开发环境下使用快速移除失效服务
    # 关闭Eureka自我保护机制，保证没有发送心跳的客户端被注册中心及时删除
    enableSelfPreservation: false
    # 如果2秒内没有收到某个微服务的心跳，那就剔除该微服务，单位为毫秒
    eviction-interval-timer-in-ms: 2000